image: node:14

cache:
    paths:
        - node_modules/

stages:
    - test

lint-and-test:
    stage: test
    script:
        - npm  install
        - npm run test
        - npm run lint
        - npm run build-all
