name: Lint and test

on: [push, pull_request]

jobs:
  default-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14

    - run: npm install
    - run: npm run test
    - run: npm run lint
    - run: npm run build-all